image: scalecommerce/xenial:1.12

stages:
  - Puppet 5
  - Puppet 6
  - push2github

trusty:puppet5:
  image: scalecommerce/base:0.6
  stage: Puppet 5
  script:
    - ./test/install-puppet5.sh
    - ./test/install.sh
    - puppet apply -v ./test/site.pp
    - inspec exec ./test/inspec/sc_mysecureshell.rb

trusty:puppet6:
  image: scalecommerce/base:0.6
  stage: Puppet 6
  script:
    - ./test/install-puppet6.sh
    - ./test/install.sh
    - puppet apply -v ./test/site.pp
    - inspec exec ./test/inspec/sc_mysecureshell.rb

xenial:puppet5:
  image: scalecommerce/xenial:1.12
  stage: Puppet 5
  script:
    - ./test/install-puppet5.sh
    - ./test/install.sh
    - puppet apply -v ./test/site.pp
    - inspec exec ./test/inspec/sc_mysecureshell.rb

xenial:puppet6:
  image: scalecommerce/xenial:1.12
  stage: Puppet 6
  script:
    - ./test/install-puppet6.sh
    - ./test/install.sh
    - puppet apply -v ./test/site.pp
    - inspec exec ./test/inspec/sc_mysecureshell.rb
    - inspec exec ./test/inspec/sc_mysecureshell.rb

bionic:puppet5:
  image: scalecommerce/bionic:1.0
  stage: Puppet 5
  script:
    - ./test/install-puppet5.sh
    - ./test/install.sh
    - puppet apply -v ./test/site.pp
    - inspec exec ./test/inspec/sc_mysecureshell.rb

bionic:puppet6:
  image: scalecommerce/bionic:1.0
  stage: Puppet 6
  script:
    - ./test/install-puppet6.sh
    - ./test/install.sh
    - puppet apply -v ./test/site.pp
    - inspec exec ./test/inspec/sc_mysecureshell.rb

push2github:
  stage: push2github
  script:
    - git push --quiet --mirror https://$GITHUB_SUPPORT_TOKEN@github.com/ScaleCommerce/puppet-sc_mysecureshell.git
