stages:
  - test
  - push2github

focal:puppet7:
  stage: test
  image: scalecommerce/focal-supervisord:1.5
  tags:
    - dind
  script:
    - ./test/install-puppet7.sh
    - ./test/install.sh
    - puppet apply -v ./test/site.pp
    - inspec exec ./test/inspec/sc_mysecureshell.rb
push2github:
  stage: push2github
  image: scalecommerce/focal-supervisord:1.5
  tags:
    - dind
  script:
    - env
    - git clone --mirror $CI_REPOSITORY_URL
    - cd puppet-sc_mysecureshell.git
    - git remote set-url --push origin https://$GITHUB_TOKEN@github.com/ScaleCommerce/puppet-sc_mysecureshell.git
    - git push --quiet --mirror