stages:
  - test
  - push2github

bionic:puppet6:
  stage: test
  image: scalecommerce/bionic:1.0
  tags:
    - dind
  script:
    - ./test/install-puppet6.sh
    - ./test/install.sh
    - puppet apply -v ./test/site.pp
    - inspec exec ./test/inspec/sc_mysecureshell.rb
push2github:
  stage: push2github
  tags:
    - dind
  script:
    - git push --quiet --mirror https://$GITHUB_TOKEN@github.com/ScaleCommerce/puppet-sc_mysecureshell.git
