image: scalecommerce/xenial:1.11

stages:
  - push2github

push2github:
  stage: push2github
  script:
    - git push --mirror https://$GITHUB_TOKEN@github.com/ScaleCommerce/puppet-sc_mysecureshell.git
