# == Class: sc_mysecureshell
#
# Installation and configuration of mysecureshell
# Original config file /etc/ssh/sftp_config will contain only includes which are
# taken from /etc/ssh/sftp.d. Main config can be found in /etc/ssh/sfpt.d/default.conf.
# More config include files can be generated by sc_mysecureshell::config_tag
#
# === Examples
#
#  class { 'sc_mysecureshell':
#
#  }
#
# --- hiera example
#
# classes:
#   - sc_mysecureshell
#
# === Authors
#
# Author Name <az@scale.sc>
#
# === Copyright
#
# Copyright ScaleCommerce GmbH 2016
#
class sc_mysecureshell (

) {
  case $::operatingsystem {
    'Ubuntu': {
      case $::operatingsystemrelease {
        '14.04': {
          $source_dir = 'ubuntu_14.04'
        }
        '16.04': {
          $source_dir = 'ubuntu_16.04'
        }
        default: { fail('Operating System not supported.')}
      }
    }
    default: { fail('Operating System not supported.') }
  }

  # copy mysecure binaries
  file { '/usr/bin/mysecureshell':
    source => "puppet:///modules/$module_name/$source_dir/mysecureshell",
    mode => '4755',
  }

  file { '/usr/bin/sftp-admin':
    source => "puppet:///modules/$module_name/$source_dir/sftp-admin",
    mode => '700',
  }

  file { '/usr/bin/sftp-kill':
    source => "puppet:///modules/$module_name/$source_dir/sftp-kill",
    mode => '700',
  }

  file { '/usr/bin/sftp-state':
    source => "puppet:///modules/$module_name/$source_dir/sftp-state",
    mode => '700',
  }

  file { '/usr/bin/sftp-user':
    source => "puppet:///modules/$module_name/$source_dir/sftp-user",
    mode => '755',
  }

  file { '/usr/bin/sftp-verif':
    source => "puppet:///modules/$module_name/$source_dir/sftp-verif",
    mode => '755',
  }

  file { '/usr/bin/sftp-who':
    source => "puppet:///modules/$module_name/$source_dir/sftp-who",
    mode => '755',
  }


  file { '/etc/ssh/sftp.d':
    ensure => directory,
  }->

  file { '/etc/ssh/sftp.d/default.conf':
    owner   => 'root',
    group   => 'root',
    mode    => '0644',
    content => template("${module_name}/default.conf.erb"),
  }->
  file { '/etc/ssh/sftp.d/User-includes.conf':
    owner   => 'root',
    group   => 'root',
    mode    => '0644',
    ensure  => 'present',
  }->

  file { '/etc/ssh/sftp_config':
    owner   => 'root',
    group   => 'root',
    mode    => '0644',
    ensure  => 'present',
    content => "##########################################################
# THIS FILE IS MANAGED BY PUPPET - DO NOT EDIT MANUALLY! #
########################END###############################
Include /etc/ssh/sftp.d/default.conf	         #include default params
Include /etc/ssh/sftp.d/User-includes.conf     #includes single user conf files",
  }

  file_line { 'shell_entry':
    path    => '/etc/shells',
    line    => '/usr/bin/mysecureshell',
  }
}
